version: "2.3"
services:
  datastore:
    image: busybox
    volumes:
      - postgresql:/var/lib/postgresql/data
  db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 5432:5432
    volumes_from:
      - datastore
  web:
    build: ./
    volumes:
      - ./:/code
    working_dir: /code
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - db
    command: python3 manage.py runserver 0.0.0.0:8000
volumes:
  postgresql:
