# Generated by Django 2.2.2 on 2019-06-09 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='回答者'),
        ),
        migrations.AlterField(
            model_name='score',
            name='contribute_score',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='投稿者'),
        ),
    ]
