# Generated by Django 2.2.3 on 2019-08-01 03:09

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=markdownx.models.MarkdownxField(help_text='Markdown形式に対応しています。', verbose_name='詳細'),
        ),
    ]
