# Generated by Django 2.2.2 on 2019-06-08 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='contribution_rate',
            new_name='contribute_score',
        ),
    ]
