# Generated by Django 2.2.3 on 2019-08-02 05:26

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20190801_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='desc',
            field=markdownx.models.MarkdownxField(help_text='※Markdown形式に対応しています。', verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=markdownx.models.MarkdownxField(help_text='※Markdown形式に対応しています。', verbose_name='詳細'),
        ),
    ]
