# Generated by Django 2.2.2 on 2019-06-10 01:40

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
