# Generated by Django 2.2.2 on 2019-06-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190611_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, upload_to='', verbose_name='icon'),
        ),
    ]
